language: python
python:
- '3.6'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIGBW4QA2H
  secret_access_key:
    secure: T1tLZZb8vEqjtH5HMXZ9lKdg7F0diHU++4yQOeObiAjqL5lWu7h6/Ns9m8JXkeHENwP30z9y7hXJAftmW82wivmpKy5pPt0nPpz9kD/uIWzhPNfMU0WIpLsV6rppHuMGs/gXkaSlRPS87NK9wyrhnXaaLVooAPWICGOyO9rvxF38SPr4e1eePlL/hFhMhQOvOAtuRhrObNHspiOY7ZXphNR1zP0iwbTHcnUpYukzVCR/UFsdi73kVmVhu+ssLrw7eeZuCOPMGYKQdkLx399X2cjgJETMTLUiNY+ZiVAaPWtO8gCnWJfvl6yxP3EKn5M61Xm339ZysO6euo3tePJPyFhA7twsVZuLvV0ua2357Zl+3VauFtYz3hTFT1XVRH0adTPdqLfuJT7NmGYBK/pkS6UR/SDaFTCaz2nn+Wdxs19eTm/d3HfTNT1AandyUWHlXvsXdV2k0uPhQunyTAV1Uio8vlaaSBvB0wLBmgqFcfWLNfQ31198NIz4lP9V6V6+qILYVqaLPStJ4/uCgFm9BTqWPU8taOMs6ZiGFwM/R+4+brlcmNue4cEA038MQfwSKTCvS1bAjDrShqanm/zSOEYvn1ZvwVH5FSKw4sNVBTEn/NBgnd8CRXRUat6oLaDvZ6pXbA69HtCGdvuJqScG9cc1lhuzY/2aYt4TpNTvFl0=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: openaccess_dictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/openaccess_dictionary
    all_branches: true
